package com.vagrancy.study.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vagrancy.study.model.knowledge.entity.Knowledge;
import com.vagrancy.study.model.knowledge.entity.KnowledgeClass;

import com.vagrancy.study.db.KnowledgeDao;
import com.vagrancy.study.db.KnowledgeClassDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig knowledgeDaoConfig;
    private final DaoConfig knowledgeClassDaoConfig;

    private final KnowledgeDao knowledgeDao;
    private final KnowledgeClassDao knowledgeClassDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        knowledgeDaoConfig = daoConfigMap.get(KnowledgeDao.class).clone();
        knowledgeDaoConfig.initIdentityScope(type);

        knowledgeClassDaoConfig = daoConfigMap.get(KnowledgeClassDao.class).clone();
        knowledgeClassDaoConfig.initIdentityScope(type);

        knowledgeDao = new KnowledgeDao(knowledgeDaoConfig, this);
        knowledgeClassDao = new KnowledgeClassDao(knowledgeClassDaoConfig, this);

        registerDao(Knowledge.class, knowledgeDao);
        registerDao(KnowledgeClass.class, knowledgeClassDao);
    }
    
    public void clear() {
        knowledgeDaoConfig.clearIdentityScope();
        knowledgeClassDaoConfig.clearIdentityScope();
    }

    public KnowledgeDao getKnowledgeDao() {
        return knowledgeDao;
    }

    public KnowledgeClassDao getKnowledgeClassDao() {
        return knowledgeClassDao;
    }

}
